@startuml VocabularyMain

object RPS
object Round
object Player
object Human
object Bot
object Goal
object Choose
object Option
object Rock
object Paper
object Scissors
object Table

RPS *-- Round
RPS *--Player
RPS *-- Table

Player <|-- Human
Player <|-- Bot
Player *-- Goal

Option <|-- Rock
Option <|-- Paper
Option <|-- Scissors

Goal ..> Choose 
Choose ..> Option

Table *-- Option

Round -->"2" Player

@enduml